### ISSUE TITLE
Crash when adding repo on non-existing sysroot

### ISSUE THREAD

**Issue by isbm** [infra-whizz/sys-mgr#1]
A cosmetic change: should not show a traceback, but a nice error message instead:

```
# zypper-sysroot ar http://download.opensuse.org/ports/armv7hl/distribution/leap/15.2/repo/oss/ arm 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5e1b8d]

goroutine 1 [running]:
github.com/infra-whizz/sys-mgr/pm.(*ZypperPackageManager).SetSysroot(0xc00000ce40, 0x0, 0x0, 0x0)
	/home/abuild/rpmbuild/BUILD/sysroot-manager-0.1/pm/zypper.go:47 +0x4d
main.runPackageManager(0x6733c0, 0xc00000cf80)
	/home/abuild/rpmbuild/BUILD/sysroot-manager-0.1/cmd/sys-mgr.go:117 +0x5c
main.main()
	/home/abuild/rpmbuild/BUILD/sysroot-manager-0.1/cmd/sys-mgr.go:315 +0xb36
```

**Comment by isbm** [comment]
Crash on actually anything if calling underlying package manager over non-existing system root.

**Comment by isbm** [comment]
Fixed in https://github.com/infra-whizz/sys-mgr/pull/5
